### ISSUE TITLE
Are Pictures on the Items-Pages possible?

### ISSUE THREAD

**Issue by doerek** [richardthombs/scunpacked#55]
Hello everybody,

first i want to thank you for this Project. I'm currently working an an small German Community page [Link](https://www.starcitizen-kantine.de/) myself and i'm always coming back to your site to check different informations. I really like the "easy-to-understand"-Structure especially when i dont know the exact title of an Item. All-in-All ....a great site & easy to navigate.

Would it be possible to add a Picture to the Detail Pages of the different Items? I know this could potentially use-up a lot of Webspace & traffic.  
At the moment i'm searching a couple of Pictures for different Items. My first Thought was: 
"No problem, SCunpacked has everything i need...."

This was the moment where i realized that in the Months before i mostly came here to get "text-Information"about "Magazine Size oder rate Of Fire....for example.

I think it would be Great if SCunpacked were "The Place to go" to get an Image for every Item.
This is the main reason why i'm asking. :)

btw. I added your Project to our Link-Database: [Link](https://www.starcitizen-kantine.de/link-entry/45-scunpacked/)

Greetings from Germany
(Sorry, if my english is a little rough)

**Comment by richardthombs** [comment]
Hi @doerek 

I would love to add some images. The goal of the project is to literally unpack the game data and as yet, I've not found any easily-accessible images that I can use. There is a whole bunch of 3d model information but there does not seem to be an easy route through to converting it into something I can include in the website. I know it must be possible because I've seen YouTube videos where people have pieced the models together. But there's no automated tool that I've found so far.

Thanks for the links!
